abstract class AccountSettingsState {}
class AccountSettingsStateInit extends  AccountSettingsState{}
class  SwitchConnected extends AccountSettingsState{}
class LoadingUpdate extends AccountSettingsState{}
class LoadingSuccess extends AccountSettingsState{}
class LoadingError extends AccountSettingsState{}
class SelectDropDownItem extends AccountSettingsState{}
class ProfileImagePicked extends AccountSettingsState{}
class LoadingChangePassword extends AccountSettingsState{}
class LoadingChangeSuccess extends  AccountSettingsState{}
class LoadingChangeError extends  AccountSettingsState{}